rango/urls.py
from django.conf.urls import url
from rango import views

app_name = 'rango'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^about/$', views.about, name='about'),
    url(r'^add_category/$', views.add_category, name='add_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/$', views.show_category, name='show_category'),
    url(r'^category/(?P<category_name_slug>[\w\-]+)/add_page/$', views.add_page, name='add_page'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login/$', views.user_login, name='login'),
    url(r'^logout/$', views.user_logout, name='logout'),
    url(r'^restricted/$', views.restricted, name='restricted'),
]

tango_with_django_project/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include
from rango import views
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^rango/', include('rango.urls')),
    url(r'^admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rango/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.
class Category(models.Model):
    name = models.CharField(max_length=128, unique=True)
    views = models.IntegerField(default=0)
    likes = models.IntegerField(default=0)
    slug = models.SlugField(unique=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.name

    def __unicode__(self):
        return self.name

class Page(models.Model):
    category = models.ForeignKey(Category)
    title = models.CharField(max_length=128)
    url = models.URLField()
    views = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def __unicode__(self):
        return self.title

class UserProfile(models.Model):
    user = models.OneToOneField(User)

    # Additional attributes
    website = models.URLField(blank=True)
    picture = models.ImageField(upload_to='profile_images', blank=True)

    def __str__(self):
        return self.user.username

    def __unicode__(self):
        return self.user.username

rango/forms.py
from django import forms
from rango.models import Page, Category, UserProfile
from django.contrib.auth.models import User


class CategoryForm(forms.ModelForm):
    name = forms.CharField(max_length=128,
                           help_text="Please enter the category name.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    likes = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    views = forms.CharField(widget=forms.HiddenInput(), required=False)

    class Meta:
        model = Category
        fields = ('name',)

class PageForm(forms.ModelForm):
    title = forms.CharField(max_length=128,
                           help_text="Please enter the title of the page.")
    url = forms.URLField(max_length=200,
                         help_text="Please enter the URL of the page.")
    views = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    def clean(self):
        cleaned_data = self.cleaned_data
        url = cleaned_data.get('url')

        # If not empty and doesnt start with http://
        if url and not url.startswith('http://'):
            url = 'http://' + url
            cleaned_data['url'] = url

            return cleaned_data

    class Meta:
        model = Page

        exclude = ('category',)

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password')


class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('website', 'picture')
        

rango/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render
from django.http import HttpResponse
from rango.models import Category, Page
from rango.forms import CategoryForm, PageForm, UserForm, UserProfileForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from datetime import datetime

# A helper method
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val
    
def visitor_cookie_handler(request):
    visits = int(get_server_side_cookie(request, 'visits', '1' ))
    last_visit_cookie = get_server_side_cookie(request, 'last_visit', str(datetime.now()))
    last_visit_time= datetime.strptime(last_visit_cookie[:-7], '%Y-%m-%d %H:%M:%S')

    if (datetime.now() - last_visit_time).seconds > 0:
        visits = visits + 1
        request.session['last_visit'] = str(datetime.now())
    else:
        request.session['last_visit'] =  last_visit_cookie

    request.session['visits'] =  visits
    
def index(request):
    request.session.set_test_cookie()
    #Query db
    category_list = Category.objects.order_by('-likes')[:5]
    page_list = Page.objects.order_by('-views')[:5]
    # Construct a dictionary to pass to the template engine as its context
    context_dict = {'categories': category_list,
                    'pages': page_list }
    
    # Call cookie helper function
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']
    context_dict['last_visit'] = request.session['last_visit']

    # Create response object    
    response = render(request, 'rango/index.html', context_dict)

    return response
    

def about(request):
    if request.session.test_cookie_worked():
        print("TEST COOKIE WORKED!")
        request.session.delete_test_cookie()

    # Construct a dictionary to pass to the template engine as its context
    context_dict = {'excerciseline': "This tutorial has been put together by Cameron McCosh."}
    
    # Call cookie helper function
    visitor_cookie_handler(request)
    context_dict['visits'] = request.session['visits']

    # Create response object    
    response = render(request, 'rango/about.html', context_dict)

    return response

def show_category(request, category_name_slug):
    # Create context dictionary
    context_dict = {}

    try:
        # Exists?
        category = Category.objects.get(slug=category_name_slug)

        # Retrieve all associated pages
        pages = Page.objects.filter(category=category)

        # Add results list to template context
        context_dict['pages'] = pages
        
        #Add category object from db to context dict
        context_dict['category'] = category

    except Category.DoesNotExist:
        context_dict['category'] = None
        context_dict['pages'] = None

    return render(request, 'rango/category.html', context_dict)

@login_required
def add_category(request):
    form =CategoryForm()

    # A HTTP POST?
    if request.method == 'POST':
        form = CategoryForm(request.POST)

        # Form valid?
        if form.is_valid():
            form.save(commit=True)
            return index(request)

        else:
            print(form.errors)

    return render(request, 'rango/add_category.html', {'form': form})

@login_required
def add_page(request, category_name_slug):
    try:
        category = Category.objects.get(slug=category_name_slug)
    except Category.DoesNotExist:
        category = None

    form = PageForm()
    if request.method == 'POST':
        form = PageForm(request.POST)
        if form.is_valid():
            if category:
                page = form.save(commit=False)
                page.category = category
                page.views = 0
                page.save()
                return show_category(request, category_name_slug)

        else:
            print(form.errors)

    context_dict = {'form': form, 'category': category}
    return render(request, 'rango/add_page.html', context_dict)

def register(request):
    registered = False

    # If POST, process data
    if request.method == 'POST':
        user_form = UserForm(data=request.POST)
        profile_form = UserProfileForm(data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()

            user.set_password(user.password)
            user.save()

            # Now sort out user profile
            profile = profile_form.save(commit=False)
            profile.user = user

            # Profile picture provided?
            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            # Save UserProfile
            profile.save()

            # Update success variable
            registered = True

        else:
            #Invalid form etc
            print(user_form.errors, profile_form.errors)

    else:
        user_form = UserForm()
        profile_form = UserProfileForm()


    return render(request,
                  'rango/register.html',
                  {'user_form': user_form,
                   'profile_form': profile_form,
                   'registered': registered})
    
def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username, password=password)

        if user:
            if user.is_active:
                login(request, user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Your Rango account is disabled.")

        else:
            print("Invalid login details: {0}, {1}".format(username, password))
            return HttpResponse("Invalid login details supplied.")

    else:
        return render(request, 'rango/login.html', {})
        
@login_required
def restricted(request):
        return render(request, 'rango/restricted.html', {} )

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))
    
    

templates/rango/about.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	About
{% endblock %}

{% block body_block %}
	<div>
		<p>{{ excerciseline }}</p><br>
		<p>Number of visits: {{ visits }}</p><br>
	</div>
	<div>
		<img src="{% static "images/rango2.jpg" %}" alt="Another picture of Rango" />
	</div>
	<div>
		<img src="{{ MEDIA_URL}}cat.jpg" alt="Picture of a cat">
	</div>
{% endblock %}

templates/rango/add_category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Add Category
{% endblock %}

{% block body_block %}
	<h1>Add a Category</h1>
	<div>
		<form id="category_form" method="post" action="/rango/add_category/">
			{% csrf_token %}
			{% for hidden in form.hidden_fields %}
				{{ hidden }}
			{% endfor %}
			{% for field in form.visible_fields %}
				{{ field.errors }}
				{{ field.help_text }}
				{{ field }}
			{% endfor %}
			<input type="submit" name="submit" value="Create Category" />
		</form>
	</div>
{% endblock %}

templates/rango/add_page.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Add Page
{% endblock %}

{% block body_block %}
	{% if category %}
	<h1>Add a Page to {{ category.name }}</h1>
		<form id="page_form" method="post" action="/rango/category/{{ category.slug }}/add_page/">
			{% csrf_token %}
			{% for hidden in form.hidden_fields %}
				{{ hidden }}
			{% endfor %}
			{% for field in form.visible_fields %}
				{{ field.errors }}
				{{ field.help_text }}
				{{ field }}
			{% endfor %}
			<input type="submit" name="submit" value="Create Page" />
		</form>
	{% else %}
		Category does not exist.
	{% endif %}
{% endblock %}

templates/rango/base.html
<!DOCTYPE html>
{% load staticfiles %}
{% load rango_template_tags %}

<html>
	<head lang="en">
		<meta charset="UTF-8" />
		<title>
		Rango - 
		{% block title_block %}
			How to Tango with Django!
		{% endblock %}
		</title>
	</head>
	<body>
		<div>
		{% block sidebar_block %}
			{% get_category_list category %}
		{% endblock %}
		</div>
		<div>
		{% block body_block %}
		{% endblock %}
		</div>
		<hr />
		<div>
			<ul>
				{% if user.is_authenticated %}
				<li><a href="{% url 'rango:restricted' %}">Restricted</a></li>
				<li><a href="{% url 'rango:logout' %}">Logout</a></li>
				<li><a href="{% url 'rango:add_category' %}">Add New Category</a></li>
				{% else %}
				<li><a href="{% url 'rango:register' %}">Sign Up</a></li>
				<li><a href="{% url 'rango:login' %}">Login</a></li>
				{% endif %}

				<li><a href="{% url 'rango:about' %}">About</a></li>
				<li><a href="{% url 'rango:index' %}">Index</a></li>
			</ul>
		</div>
	</body>
</html>

templates/rango/category.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	{{ category.name }}
{% endblock %}

{% block body_block %}
	{% if category %}
		<h1>{{ category.name }}</h1>
		{% if pages %}
			<ul>
			{% for page in pages %}
				<li><a href="{{ page.url }}">{{ page.title }}</a></li>
			{% endfor %}
			</ul>
		{% else %}
			<strong>No pages currently in category.</strong>
		{% endif %}
	{% else %}
		The specified category does not exist!
	{% endif %}
	{% if user.is_authenticated %}
		<a href="{% url 'rango:add_page' category.slug %}">Add Page</a><br/>
	{% endif %}
{% endblock %}

templates/rango/cats.html
<ul>
	{% if cats %}
		{% for c in cats %}
			{% if c == act_cat %}
				<li>
					<strong>
						<a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
					</strong>
				</li>
			{% else %}
				<li>
					<a href="{% url 'rango:show_category' c.slug %}">{{ c.name }}</a>
				</li>
			{% endif %}
		{% endfor %}
	{% else %}
		<li><strong>There are no categories present.</strong></li>
	{% endif %}
</ul>

templates/rango/index.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block body_block %}
	<h1>Rango says...</h1>
	{% if user.is_authenticated %}
		howdy {{ user.username }}
	{% else %}
	hey there partner!
	{% endif %}
	
	<h2>Most Liked Categories</h2>
	<div>
	{% if categories %}
	<ul>
		{% for category in categories %}
			<li>
			<a href="{% url 'rango:show_category' category.slug %}">
				{{ category.name }}
			</a>
			</li>
		{% endfor %}
	</ul>
	{% else %}
		<strong>There are no categories present.</strong>
	{% endif %}
	</div>
	
	<h2>Most Viewed Pages</h2>
	<div>
	{% if pages %}
	<ul>
		{% for page in pages %}
			<li><a href="{{ page.url }}">{{ page.title }}</a></li>
		{% endfor %}
	</ul>
	{% else %}
		<strong>No top viewed pages.</strong>
	{% endif %}
	</div>
	<p>visits: {{ visits }}</p>
	<p>last visit: {{ last_visit }}</p>
	<div>
		<img src="{% static "images/rango.jpg" %}" alt="Picture of Rango" />
	</div>
{% endblock %}

templates/rango/login.html
{% extends 'rango/base.html' %}
{% load staticfiles %}


{% block title_block %}
	Login
{% endblock %}

{% block body_block %}
<h1>Login to Rango</h1>
{% if error %}
	{{ error }}<br />
{% endif %}
<form id="login_form" method="post" action="{% url 'rango:login' %}">
	{% csrf_token %}
	Username: <input type="text" name="username" value="" size="50" />
	<br />
	Password: <input type="password" name="password" value="" size="50" />
	<br />
	<input type="submit" value="submit">
</form>
{% endblock %}

templates/rango/register.html
{% extends 'rango/base.html' %}
{% load staticfiles %}


{% block title_block %}
	Register
{% endblock %}



{% block body_block %}
	<h1>Register for Rango</h1>
	{% if registered %}
		Rango says: <strong>thank you for registering!</strong>
		<a href="{% url 'rango:index' %}">Return to the homepage.</a><br />
	{% else %}
		Rango says: <strong>register here!</strong><br />
		<form id="user_form" method="post" action="{% url 'rango:register' %}" enctype="multipart/form-data">
		{% csrf_token %}
		
		<!-- Display each form -->
		{{ user_form.as_p }}
		{{ profile_form.as_p }}
			
			<input type="submit" name="submit" value="Register" />
		</form>

	{% endif %}
{% endblock %}

templates/rango/restricted.html
{% extends 'rango/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Restricted
{% endblock %}

{% block body_block %}
	Since you're logged in, you can see this text!
{% endblock %}